import ollama # type: ignore

prompts = [
    "What causes stars to die?",
    "You are an astrophysicist. What causes stars to die?",
    "You are an astrophysicist explaining to a 10 year old. What causes stars to die?",
    "You are a skeptical scientist. List only what is observationally confirmed about stellar death. No speculation."
]

for prompt in prompts:
    response = ollama.chat(
        model="llama3.2",
        messages=[{"role": "user", "content": prompt}],
        options={"temperature": 0.3}
    )
    print(f"Prompt: {prompt[:60]}...")
    print(response.message.content)
    print("-" * 50)

#Here, in the 4th part, the "observational" did the whole work. 
#We are controlling here what the model is and isn't allowed to do.

#However, even if we write "No speculations", the model still can't fully comply with its own constraints.
#It was trained on text that mixes observation and theory, so it can't perfectly do it.

#For this, we have to verify that the things generated by the llm is purely observational.
#For that, we have to pull actual observational data and then verify. This is where RAG comes in.
